name: CodeSee Map

on:
  push:
    branches:
      - main

jobs:
  codesee-map:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v2

    - name: CodeSee Map
      uses: Codesee-io/codesee-map-action@v1
      with:
        api-key: ${{ secrets.CODESEE_API_KEY }}
        organization-id: <YOUR_ORGANIZATION_ID>
        project-id: <YOUR_PROJECT_ID>
